function ySol = ySol(t)
%ySol
%    ySol = ySol(T)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Jun-2025 12:14:45

t2 = sqrt(3.99e+2);
t3 = (t.*t2)./2.0e+1;
ySol = (exp(t.*(-1.0./2.0e+1)).*(cos(t3).*3.99e+2+t2.*sin(t3)))./3.99e+2;
end
